### ISSUE TITLE
Correct extensions aren't always added

### ISSUE THREAD

**Issue by ISNIT0** [jjrv/systema#17]
```tsx
// App.tsx
import { SampleComponent } from './Component';

const element = <div>
    <h1 class='test' style={{ color: 'red' }}>Hello, World!</h1>
    <SampleComponent />
</div>;

ReactDOM.render(element, document.body);
```

```tsx
// Component.tsx

export class SampleComponent extends React.Component {
    render() {
        return <h4>Hello from a component</h4>
    }
}
```

In a browser, we look for `Component.js` not `Component.tsx`. I guess we should assume the same extension as the parent file?

**Comment by jjrv** [comment]
Good point. I guess it applies to relative URLs only. Otherwise importing something like `left-pad/test` implies a staggering number of potential files to check. These would need to be tried for every path component:

- `node_modules/left-pad/test.js`
- `node_modules/left-pad/test/index.js`
- `node_modules/left-pad/test.ts`
- `node_modules/left-pad/test.tsx`

No way to check over HTTP if the directory itself exists, have to try all possible file names.

**Comment by jjrv** [comment]
Fixed in `requirex`
